Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCKhumaloCraftFinal2.Data;
using MVCKhumaloCraftFinal2.Models;

namespace MVCKhumaloCraftFinal2.Controllers
{
    public class AdminsController : Controller
    {
        private readonly MVCKhumaloCraftFinal2Context _context;

        public AdminsController(MVCKhumaloCraftFinal2Context context)
        {
            _context = context;
        }

        // GET: Admins/Login
        public IActionResult Login()
        {
            return View("AdminLogin");
        }

        // POST: Admins/Login
        [HttpPost]
        public IActionResult Login(Admin model)
        {
            var admin = _context.Admin.FirstOrDefault(a => a.adminEmail == model.adminEmail && a.adminPassword == model.adminPassword);
            if (admin != null)
            {
                // Setting the session variable to identify admin
                HttpContext.Session.SetString("IsAdmin", "true");
                HttpContext.Session.SetString("AdminEmail", admin.adminEmail); // Storing admin email in session (for displaying admin email after log in)
                return RedirectToAction("Index", "Home");
            }

            // If login fails, adding an error message to ModelState
            ModelState.AddModelError(string.Empty, "Incorrect email or password.");
            return View("AdminLogin", model);
        }

        // POST: Admins/Logout
        [HttpPost]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear(); // Clear the session
            return RedirectToAction("Index", "Home"); // Redirect to home page
        }

        // GET: Admins/Dashboard
        public IActionResult Dashboard()
        {
            var orders = _context.Order.ToList();
            return View("Index", orders);
        }

        // GET: Admins
        public async Task<IActionResult> Index()
        {
            return View(await _context.Admin.ToListAsync());
        }

        // GET: Admins/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admin
                .FirstOrDefaultAsync(m => m.adminID == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        // GET: Admins/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admins/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("adminID,adminEmail,adminPassword")] Admin admin)
        {
            if (ModelState.IsValid)
            {
                _context.Add(admin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(admin);
        }

        // GET: Admins/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admin.FindAsync(id);
            if (admin == null)
            {
                return NotFound();
            }
            return View(admin);
        }

        // POST: Admins/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("adminID,adminEmail,adminPassword")] Admin admin)
        {
            if (id != admin.adminID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(admin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdminExists(admin.adminID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(admin);
        }

        // GET: Admins/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var admin = await _context.Admin
                .FirstOrDefaultAsync(m => m.adminID == id);
            if (admin == null)
            {
                return NotFound();
            }

            return View(admin);
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var admin = await _context.Admin.FindAsync(id);
            if (admin != null)
            {
                _context.Admin.Remove(admin);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AdminExists(int id)
        {
            return _context.Admin.Any(e => e.adminID == id);
        }
    }
}

Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using MVCKhumaloCraftFinal2.Data;
using MVCKhumaloCraftFinal2.Models;
using static System.Reflection.Metadata.BlobBuilder;

namespace MVCKhumaloCraftFinal2.Controllers
{
    public class ProductsController : Controller
    {
        private readonly MVCKhumaloCraftFinal2Context _context;

        public ProductsController(MVCKhumaloCraftFinal2Context context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.productID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create //only admins can create products
        public IActionResult Create()
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return Forbid();
            }

            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("productID,productName, description, Price,Category,stockAvailable,ImageUrl")] Product product)
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return Forbid();
            }

            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("productID,productName, description, Price,Category,stockAvailable,ImageUrl")] Product product)
        {
            if (id != product.productID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.productID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return Forbid();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.productID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (HttpContext.Session.GetString("IsAdmin") != "true")
            {
                return Forbid();
            }

            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.productID == id);
        }

        [HttpPost]
        public async Task<IActionResult> AddToCart(int productId)
        {
            var product = await _context.Product.FirstOrDefaultAsync(b => b.productID == productId);
            if (product == null)
            {
                return NotFound();
            }

            // Adding the craftwork to the cart
            var cartItem = new CartItem { ProductID = productId };
            _context.CartItem.Add(cartItem);
            await _context.SaveChangesAsync();

            return Ok();
        }
    }
}

Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KhumaloCraft</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCKhumaloCraftFinal2.styles.css" asp-append-version="true" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@100..900&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light custom-navbar-bg box-shadow mb-3 @(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"] ? "transparent-navbar" : "")">
            <div class="container-fluid">
                @if (!(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"]))
                {
                    <div class="navbar-brand-container">
                        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                            <img src="~/Images/KhumaloCraft.png" alt="KhumaloCraft Logo" class="navbar-logo @(ViewContext.RouteData.Values["action"]?.ToString() == "Index" ? "navbar-logo-home" : "navbar-logo-other")" />
                        </a>
                    </div>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <div class="central-links">
                        <ul class="navbar-nav">
                            <li class="nav-item @(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"] ? "login-nav-item" : "")">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item @(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"] ? "login-nav-item" : "")">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                            </li>
                            <li class="nav-item @(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"] ? "login-nav-item" : "")">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Craftwork</a>
                            </li>
                            <li class="nav-item @(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"] ? "login-nav-item" : "")">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                            </li>
                            <li class="nav-item @(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"] ? "login-nav-item" : "")">
                                <a class="nav-link text-dark" asp-area="" asp-controller="CartItems" asp-action="Index">Cart</a>
                            </li>
                        </ul>
                    </div>

                    <!--checking if user registered/logged in to display their name-->
                    <ul class="navbar-nav right-align">
                        @if (HttpContextAccessor.HttpContext.Session.GetString("IsAdmin") == "true")
                        {
                            <li class="nav-item">
                                <span class="nav-link text-dark">@HttpContextAccessor.HttpContext.Session.GetString("AdminEmail")</span>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Admins" asp-action="Logout">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-dark">@User.Identity.Name</span>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Users" asp-action="Logout">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item @(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"] ? "login-nav-item" : "")">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Create">Register</a>
                            </li>
                            <li class="nav-item @(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"] ? "login-nav-item" : "")">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @if (!(ViewData["IsLoginPage"] != null && (bool)ViewData["IsLoginPage"] || ViewData["IsRegisterPage"] != null && (bool)ViewData["IsRegisterPage"]))
    {
        <div class="webFooter">
            <p class="row1">Who we are</p>
            <p class="item1">About us</p>

            <p class="row2">What we do</p>
            <p class="item2">Craftwork</p>
            <p class="item3">Become a registered artisan</p>
            <p class="item4">Furniture stability fact sheet</p>

            <p class="row3">Support</p>
            <p class="item5">Return policy</p>
            <p class="item6">Privacy policy</p>

            <h2 class="row4">Get News & Updates</h2>
            <p class="item7">Sign up for our email list today.</p>
            <div class="newsLetter" />
            <button class="newsLetterButton">Email me</button>
        </div>
    }
    <footer class="footer text-muted">
        <div class="container">
            &copy; 2024 - KhumaloCraft - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>